apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          imagePullPolicy: Never
          image: img-ftps
          ports:
          - containerPort: 21
          - containerPort: 30000
          - containerPort: 30001
          - containerPort: 30002
          - containerPort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: main-ftps-port
    port: 21
    targetPort: 21
  - name: ftps-port1
    port: 30000
    targetPort: 30000
  - name: ftps-port2
    port: 30001
    targetPort: 30001
   - name: ftps-port3
    port: 30002
    targetPort: 30002
  - name: ftps-port4
    port: 30003
    targetPort: 30003